// src/pages/ProfilePage/ProfilePage.tsx
import 'pages/ProfilePage/styles.scss'

export default function ProfilePage() {
  return (
    <div className='profile container color-light'>
      <div className="profile__header">
        <div className="profile__image"></div>
        <div className="profile__info">
          <div>
            <h1 className="profile__name fw-700">Георгий Кобунов</h1>
            <p className="profile__description fw-500 p">
              Привет! Я занимаюсь веб-разработкой!<br/>
              Я умею писать сайты на Angular, React.<br/>
              Также могу реализовать полноценное клиент-серверное REST приложение, <br/>
              используя Nest.js и вышеперечисленные фреймворки.
            </p>
          </div>
          <div className="profile__stats fw-600">
            <div className='profile__stat-group'>
              <div className="profile__stat mr-2">
                <span>Рейтинг:&nbsp;</span><span className='color-main'>4.7</span>
              </div>
              <div className="profile__stat">
                <span>Отзывов:&nbsp;</span><span className='color-main'>100</span>
              </div>
            </div>
            <div className="profile__stat">
              <span>Выполнено заказов:&nbsp;</span><span className='color-main'>10</span>
            </div>
          </div>
        </div>
      </div>
      <div className="projects">
        <h2 className="projects__title fw-600">Портфолио</h2>
        <div className="projects__grid">
          <div className="project"></div>
          <div className="project"></div>
          <div className="project"></div>
        </div>
      </div>
    </div>
  )
}

// src/app/modules/profile/pages/profile-page/profile-page.component.ts
import { Component, ChangeDetectionStrategy } from '@angular/core';

@Component({
  selector: 'app-profile-page',
  templateUrl: './profile-page.component.html',
  styleUrls: ['./profile-page.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ProfilePageComponent {}

<section class="profile container">
    <img src="/assets/header/profile.svg" class="profile__img"/>
    <div class="profile__info">
        <div class="name-with-rating">
            <h1 class="profile__name fw-600">Георгий Кобунов</h1>
            <div class="rating">
                <div class="rating__img"></div>
                <span class="rating__value color-main fw-500">4.7</span>
            </div>
        </div>
        <p class="profile__description">
            Привет! Я занимаюсь веб-разработкой!
            Я умею писать сайты на Angular, React.
            Также могу реализовать полноценное клиент-серверное REST приложение,
            используя Nest.js и вышеперечисленные фреймворки.
        </p>
        
        <div class="skills">
            <app-tag text="верстка"></app-tag>
            <app-tag text="фронтенд"></app-tag>
            <app-tag text="разработка"></app-tag>
            <app-tag text="бэкенд"></app-tag>
            <app-tag text="менторинг"></app-tag>
        </div>
    </div>
    <div class="connect-btn-container">
        <button class="connect-btn focus-yellow-box-shadow">связаться</button>
        <div class="profile__stats">
            <!-- MAKE MATERIAL TOOLTIP INSTEAD OF TITLE-->
            <div class="stat" title="Выполнено заказов">
                <div class="stat__img check-img"></div>
                <p class="stat__value">10</p>
            </div>

            <!-- MAKE MATERIAL TOOLTIP INSTEAD OF TITLE-->
            <div class="stat">
                <!-- TODO can we make its icon bolder like it is in check-icon?-->
                <div class="stat__img feedback-img" title="Количество отзывов"></div>
                <p class="stat__value">5</p>
            </div>
        </div>
    </div>
</section>
