// src/components/Order/Order.tsx
import { nanoid } from 'nanoid'

import 'components/Order/styles.scss'
import OrderTag from 'components/OrderTag/OrderTag'

export interface IOrder {
    title: string,
    description: string,
    date?: string,
    price: string,
    createdAt: string,
    tags: Array<string>
}

export default function Order(orderData: IOrder) {
    return (
        <div className="order">
            <div className="order__data">
                <h2 className="order__title">{orderData.title}</h2>
                {/* TODO CREATE MARKDOWN */}
                <p className='order__description'>
                    {orderData.description}
                </p>
                <label className="order__date">
                    <div className="order__date-img"></div>
                    <span>{orderData.date}</span>
                </label>
            </div>
            <div className="order__info">
                <span className="order__price">
                    {orderData.price}
                </span>
                <div className="order__created-at">
                    <div className="order__created-at-img"></div>
                    <span>{orderData.createdAt}</span>
                </div>
            </div>
            <div className="order__tags">
                {orderData.tags.map(tag=><OrderTag text={tag} key={nanoid()}/>)}
            </div>
        </div>
    )
}

// src/app/modules/order/components/order/order.component.ts
import { Component, Input } from '@angular/core';
import { IOrder } from '../../pages/orders-page/orders-page.component';

export interface INumericFromTo {
  from: number;
  to: number;
}

@Component({
  selector: 'app-order',
  templateUrl: './order.component.html',
  styleUrls: ['./order.component.scss'],
})
export class OrderComponent {
  @Input() order!: IOrder;
}

<div class="order">
  <div class="order__data">
    <h2 class="order__title">{{ order.title }}</h2>
    <p class="order__description">
      {{ order.description }}
    </p>
    <label class="order__date">
      <div class="order__date-img"></div>
      <span>{{ order.date?.from }}</span>
    </label>
  </div>
  <div class="order__info">
    <span class="order__price">
      {{ order.price?.from }}
    </span>
    <div class="order__created-at">
      <div class="order__created-at-img"></div>
      <span>{{ order.createdAt }}</span>
    </div>
  </div>
  <div class="order__tags">
    <app-tag *ngFor="let tag of order.tags" [text]="tag"></app-tag>
  </div>
</div>
