// src/app/shared/components/toggler/toggler.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-toggler',
  templateUrl: './toggler.component.html',
  styleUrls: ['./toggler.component.scss'],
})
export class TogglerComponent {}

<label class="switch">
    <input type="checkbox"
        defaultChecked
    />
    <span class="slider round"></span>
</label>

// src/components/Toggler/Toggler.tsx
import { Roles } from 'components/HeaderRole/Role'
import 'components/Toggler/styles.scss'

export default function Toggler({currentRole, onChange}:{currentRole: Roles, onChange: Function}) {
    return (
        <label className="switch">
            <input type="checkbox"
                defaultChecked={currentRole === Roles.performer}
                onChange={()=>onChange()}
            />
            <span className="slider round"></span>
        </label>
    )
}
