// src/pages/OrdersPage/OrdersPage.tsx
import Order, { IOrder } from 'components/Order/Order'
import { nanoid } from 'nanoid'

import 'pages/OrdersPage/styles.scss'

const orders: Array<IOrder> = [
    {
        title: 'Веб-разработка',
        description: 'Нужен блин сайт))) срочно!!!!!!!!!!!!!!! а то тототото ыффф',
        price: '1000EUR',
        createdAt: 'just now',
        date: 'tommorow',
        tags:['math', 'physics']
    },
    {
        title: 'Веб-разработка',
        description: 'Нужен блин сайт))) срочно!!!!!!!!!!!!!!! а то тототото ыффф',
        price: '1000EUR',
        createdAt: 'just now',
        date: 'tommorow',
        tags:['math', 'physics']
    },
    {
        title: 'Веб-разработка',
        description: 'Нужен блин сайт))) срочно!!!!!!!!!!!!!!! а то тототото ыффф',
        price: '1000EUR',
        createdAt: 'just now',
        date: 'tommorow',
        tags:['math', 'physics']
    },
    {
        title: 'Веб-разработка',
        description: 'Нужен блин сайт))) срочно!!!!!!!!!!!!!!! а то тототото ыффф',
        price: '1000EUR',
        createdAt: 'just now',
        date: 'tommorow',
        tags:['math', 'physics']
    },
    {
        title: 'Веб-разработка',
        description: 'Нужен блин сайт))) срочно!!!!!!!!!!!!!!! а то тототото ыффф',
        price: '1000EUR',
        createdAt: 'just now',
        date: 'tommorow',
        tags:['math', 'physics']
    },
]

export default function OrdersPage() {
    return (
        <div className="orders container color-light">
            {orders.map(order=><Order {...order} key={nanoid()}/>)}
        </div>
    )
}

// src/app/modules/order/pages/orders-page/orders-page.component.ts
import { Component } from '@angular/core';
import { INumericFromTo } from '../../components/order/order.component';

export interface IOrder {
  title: string;
  description: string;
  date: INumericFromTo | null;
  price: INumericFromTo | null;
  createdAt: number;
  tags: Array<string>;
}

@Component({
  selector: 'app-orders-page',
  templateUrl: './orders-page.component.html',
  styleUrls: ['./orders-page.component.scss'],
})
export class OrdersPageComponent {
  public orders: Array<IOrder> = [
    {
      title: 'Заголовок',
      description:
        'Описание.... ОписаниеОписание.... ОписаниеОписание.... ОписаниеОписание.... Описание',
      createdAt: Math.floor(Date.now() / 1000),
      date: {
        from: Math.floor(Date.now() / 1000),
        to:  Math.floor(Date.now() / 1000 + 60 * 60 * 24 * 5),
      },
      price: {
        from: 100,
        to: 500,
      },
      tags: ['веб-разработка', 'грузоперевозки'],
    },
  ];
}

<div class="container">
    <app-order *ngFor="let order of orders" [order]="order"></app-order>
</div>
